language: java
sudo: false # faster builds
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk11
after_success:
#  - mvn clean cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash) -t 8aa94f39-8dbc-4ee0-9517-617e02ff49fb
