language: java
jdk:
  - openjdk11
#branches:
#  only:
#    - 2.2.X
script:
#  - jdk_switcher use openjdk10
#  - # do stuff with OpenJDK 10
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
#script: mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
