language: java
jdk:
  - openjdk8
#install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
#script: mvn test cobertura:cobertura
after_success:
#  - mvn clean cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash)
