on: # 定义工作流触发条件
  push: # 当有代码推送时触发
    branches:
      - 2.7.X
      - 2.8.X

jobs: # 定义工作流中的任务
  report: # 任务名称为 report
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai # 设置时区为上海 (UTC+8)
    steps: # 定义任务中的步骤
      - uses: actions/checkout@v4 # 使用 actions/checkout@v4 这个 Action，用于检出代码
      - name: Set up JDK 11 # 步骤名称：安装 JDK 11
        uses: actions/setup-java@v4 # 使用 actions/setup-java@v4 这个 Action，用于安装 Java 环境
        with: # 配置参数
          java-version: '11' # Java 版本设置为 11
          distribution: 'temurin' # 使用 Temurin 发行版的 JDK
          cache: maven
      - name: 生成代码覆盖率报告
        # 运行的脚本：Maven 构建命令，忽略测试失败，静默模式，显示版本
        run: mvn verify -Dmaven.test.failure.ignore=true -B -V
      - name: 上传覆盖率到 Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          # 为这次上传的覆盖率数据添加一个标签，用于在 Codecov 网站上进行分类和筛选
          flags: unittests
          # 启用详细输出模式，提供更详细的日志信息，有助于调试问题
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            ./toolbox-cache/target/site/jacoco/jacoco.xml,
            ./toolbox-core/target/site/jacoco/jacoco.xml,
            ./toolbox-crypto/target/site/jacoco/jacoco.xml,
            ./toolbox-db/target/site/jacoco/jacoco.xml,
            ./toolbox-http/target/site/jacoco/jacoco.xml,
            ./toolbox-json/target/site/jacoco/jacoco.xml,
            ./toolbox-mongodb/target/site/jacoco/jacoco.xml