name: Publish package to Maven Central Repository
on:
  workflow_dispatch:
  push:
    branches:
      - 2.8.X
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          # Nexus用户名环境变量
          server-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          # Nexus密码环境变量
          server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          # gpg私钥
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          # gpg短密码环境变量
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Apache Maven Central
        run: mvn clean --batch-mode deploy -P release -Dmaven.test.skip=true